### ISSUE TITLE
1. couldn't read pom.xml file error

### ISSUE THREAD

**Issue by tannazr** [GigSynergy/Urgent_Care_Project#1]
I encountered this error while I was trying to import this cloned project as a maven project to my eclipse. I thoroughly investigated the issue by reinstalling my eclipse, maven plugins and even gitbash but no success. Then I decided to clone and check If I could import any other maven project or not. This time I succeed. Therefore, I found that the problem was coming from corrupted pom.xml file in our forked repo.
After re-forking the project the problem was resolved.
More assumption: In our group of four people ,two have PCs and two have Mac. The irony is one of  my  teammates and I that have PC, encountered this problem while two others using Mac had no problem importing the cloned project. Is this problem coming from a bug in Maven plugin for eclipse in windows? or is it a Windows issue? Any related though is appreciated.

**Comment by shubhvs** [comment]
I encountered this exact problem last week. I wasn't able to read the pom.xml file. What worked for me is - I had to delete the project in the local repository and clone the project again. This time I imported a git project from local repository and then convert the project into Maven project. I agree with you that this might be the result of using two different type of development environments that we are using. I also think that some of us were using different version of Eclipse IDE or some other tools. I am not sure if its the Maven plugin issue but we cannot deny the possibility. I am glad that we encountered this problem early on.
